sudo: false
language: node_js
node_js:
  - "4.8.0"

addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install

before_install:
  - curl https://install.meteor.com/?release=1.5.2.2 | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

script:
  - (cd meteor-tests && meteor npm install)
  - npm run coveralls
  - npm run test-meteor
